### ISSUE TITLE
Stopped working with private accounts

### ISSUE THREAD

**Issue by Retul15** [notcammy/PyInstaStories#2] opened 2018-08-13 00:58 UTC
This code worked fine to download private account's stories if my account following the private account. But now it is only working with public accounts. 
It only shows for private account `There are no recent stories to process for this user`

**Comment by dvingerh** [comment] 2018-08-13 01:26
I cannot reproduce the issue. Please give the following information:

- Instagram API version
- Python version

Also verify you are still indeed following the user and that this issue also occurs with other private accounts that you follow (make a test account if necessary)

**Comment by Retul15** [comment] 2018-08-13 02:11
My python version is Python 3.5.3 and I have installed Instagram private API with this command `pip3 install git+https://git@github.com/ping/instagram_private_api.git@1.5.7`
I don't know what it's version. And I have already tried it with two accounts. One of them is my test account. After making my account public it downloaded. Also I have tried another account to download stories but still no success. I don't know if it's only me.

**Comment by dvingerh** [comment] 2018-08-13 02:42
I've tested on two unrelated machines with different accounts and it works fine. It must be something on your end. Try on a different network (different IP) and ensure you have the latest API version installed (can check with `pip3 freeze`).

Will close this issue since it's not a problem with the script, but feel free to report back with any findings

**Closed as completed by dvingerh** 2018-08-13 02:42 UTC
Labels: bug, invalid
